# Generated by Django 3.0 on 2020-07-11 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user_role', models.CharField(choices=[('Customer', 'Customer'), ('Astrologer', 'Astrologer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Astro_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Vedic astrology', 'Vedic astrology'), ('Horoscopic astrology', 'Horoscopic astrology'), ('Vaastu', 'Vaastu'), ('Western astrology', 'Western astrology'), ('Numerology', 'Numerology'), ('Tarot divination', 'Tarot divination'), ('Prashna Kundali', 'Prashna Kundali'), ('KP astrology', 'KP astrology')], max_length=100)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Guarati'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil')], max_length=36)),
                ('experience', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
