# Generated by Django 3.0 on 2020-07-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images'),
        ),
    ]
