# Generated by Django 3.0 on 2020-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_monthlyhoroscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyhoroscope',
            name='image',
            field=models.ImageField(default='zodiac2.jpg', upload_to=''),
        ),
    ]
