# Generated by Django 3.0 on 2020-07-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_yearlyhoroscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPanchang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tithi', models.CharField(max_length=50)),
                ('nakshatra', models.CharField(max_length=50)),
                ('karana', models.CharField(max_length=50)),
                ('paksha', models.CharField(max_length=50)),
                ('yoga', models.CharField(max_length=50)),
                ('yoga_till', models.TimeField()),
                ('day', models.CharField(max_length=50)),
                ('astroprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Astro_Profile')),
            ],
        ),
    ]
