# Generated by Django 3.0 on 2020-07-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_solarcycle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolarCycle',
            new_name='DailySolarCycle',
        ),
    ]
