# Generated by Django 3.0 on 2020-07-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200720_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinduMonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shakasamwat', models.IntegerField()),
                ('vikramsamwat', models.IntegerField()),
                ('monthamanta', models.CharField(max_length=50)),
                ('monthpurnimanta', models.CharField(max_length=50)),
                ('astroprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Astro_Profile')),
            ],
        ),
    ]
