# Generated by Django 3.0 on 2020-07-21 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_yearlynumerology'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('banner', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('date', models.DateField(auto_now_add=True)),
                ('astroprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Astro_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTarot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=50)),
                ('content', models.TextField()),
                ('astroprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Astro_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TarotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TarotArticle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
