# Generated by Django 3.0 on 2020-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200721_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_birth_date', models.DateField()),
                ('partner_birth_time', models.TimeField()),
            ],
        ),
    ]
