# Generated by Django 3.0 on 2020-07-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_lovecompatibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoveCompatibility',
        ),
    ]
