# Generated by Django 3.0 on 2020-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_lovecompatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynumerology',
            name='image',
            field=models.ImageField(blank=True, default='zodiac2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='monthlynumerology',
            name='image',
            field=models.ImageField(blank=True, default='zodiac2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='weeklynumerology',
            name='image',
            field=models.ImageField(blank=True, default='zodiac2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='yearlynumerology',
            name='image',
            field=models.ImageField(blank=True, default='zodiac2.jpg', upload_to=''),
        ),
    ]
